frame = "transparent"

[font]
normal = [{ family = "Monaspace Argon"}, "Symbols Nerd Font Mono"]
italic = [{ family = "Monaspace Radon" }, "Symbols Nerd Font Mono"]
bold = [{ family = "Monaspace Krypton" }, "Symbols Nerd Font Mono"]
size = 15

[box-drawing]
# "font-glyph", "native" or "selected-native"
mode = "native"
# selected = "î‚¹ğŸ®ğŸ®‘ğŸ®’î¸€î¸î¸‚î¸ƒî¸„î¸…"
#
[font.features]
"Monaspace Argon" = ["+calt", "+liga", "+dlig", "+ss01", "+ss02", "+ss03", "+ss04", "+ss05", "+ss06", "+ss07", "+ss08" ]
"Monaspace Radon" = ["+calt", "+liga", "+dlig", "+ss01", "+ss02", "+ss03", "+ss04", "+ss05", "+ss06", "+ss07", "+ss08" ]
"Monaspace Krypton" = ["+calt", "+liga", "+dlig", "+ss01", "+ss02", "+ss03", "+ss04", "+ss05", "+ss06", "+ss07", "+ss08" ]
"Cascadia Code" = [ "+calt", "+ss01", "+ss02" ]
